### ISSUE TITLE
Enable issues over at ftrackhq/ftrack-python

### ISSUE THREAD

**Issue by ffMathy** [ftrackhq/ftrack-javascript#123]
Sorry for writing here. But why are issues disabled over at ftrackhq/ftrack-python?

I have quite a few issues I'd like to report. And I'd most likely be willing to submit pull requests too, if I could make issues for them and discuss the solutions first.

**Comment by bjornrydahl** [comment]
Hi Mathias, we have opened up issues now. Thank you!
