### ISSUE TITLE
Can't receive reply for ftrack.action.discover

### ISSUE THREAD

**Issue by ffMathy** [ftrackhq/ftrack-javascript#131]
_I am on the latest beta release (1.8) for this._

When I try to publish an `ftrack.action.discover` event, I don't receive a reply with data filled out.

Here's my code for it:

```typescript
const responseEvent = await ftrackSession.eventHub.publishAndWaitForReply(
    new Event("ftrack.action.discover", {}),
    {
        timeout: 10
    });
```

After running, `responseEvent` is:

```js
{
  target: 'id=6a302ace-fa03-4e3b-beac-3770b78d3d6b',
  inReplyToEvent: 'a600aeba-30fe-43a1-9423-9a0ca1430c0d',
  topic: 'ftrack.meta.reply',
  source: {
    id: 'fabcc81ead654894af65da98ca7f5b2d',
    user: { username: 'root' }
  },
  data: {},
  id: '900b0fde119e4f1a959e34b55a653cee',
  sent: null
}
```

Note that `data` is empty. This is despite my actions being correctly discovered.

The reason I want to publish a `ftrack.action.discover` event myself, is for end-to-end testing of our actions in general.

Is there a known limitation here, or should this work?

**Comment by ffMathy** [comment]
Hmmm, actually the action is not discoverable. So something else must be happening.

We recently converted our code from Python to TypeScript.

When subscribing to events, we return the response directly in the subscription like we did in Python. This should send a reply to the discover event, but perhaps it isn't?

**Comment by ffMathy** [comment]
I even tried responding now with a `publishReply` call directly. I still just get "Haven't found any actions yet...".

**Comment by gismya** [comment]
It's hard to know the exact issues without seeing the code. But I notice that you should use `publish` instead of `publishAndWaitForReply`, since there could be several answers. 

The issue seems to be with how you've registered your events. Please share as reproducible an example as possible, and I can look into it.

**Comment by ffMathy** [comment]
I got it working now by listening to multiple replies. The weird part is that we have nothing else that should be replying. Is Ftrack sending replies on its own?

**Comment by gismya** [comment]
I'll investigate if there are any issues

**Comment by ffMathy** [comment]
Remember that we're on the latest beta release with the new socket implementation. I think it has to do with that.
