### ISSUE TITLE
Proposal: Strong-typed queries

### ISSUE THREAD

**Issue by ffMathy** [ftrackhq/ftrack-javascript#138]
_This is going to sound a bit crazy, but hear me out. There are currently a number of issues with this proposal, but it exists solely for the sake of demonstration. We can probably get around the limitations._

I have been experimenting with making the query function strong-typed, so that queries are validated at compile-time.

# Features
- Validates that type names are correct in the query.
- Validates that the projection contains valid property names.
- Validates the criteria section (`where`), including.
    - Checking for valid property names.
    - Checking for valid operators for particular types.
        - `string` only allows:
            - `=` and `is`.
            - `!=` and `is_not`.
            - `in` and `not_in`.
            - `like` and `not_like`.
        - `number` only allows:
            - `=` and `is`.
            - `!=` and `is_not`.
            - `in` and `not_in`.
            - `>`, `after` and `greater_than`.
            - `<`, `before` and `less_than`.
            - `>=` and `<=`.
        - `boolean` only allows:
            - `=` and `is`.
            - `!=` and `is_not`.
            - `in` and `not_in`.
        - `object` only allows:
            - `has`.
            - `any`.
    - Checking for valid `where` values.
        - If the property name does not exist, it gives a compile error.
        - If for instance the property name being queried is a string, it must be wrapped in quotes.
        - If the property name being queried is a number, it must be numeric.

# Current limitations
_If you like where this is headed, I am willing to invest in trying to resolve these limitations. So please don't see them as direct show-stoppers. Let's have a discussion about it._

- I'd like this to work with `infer`, so that instead of writing `strongTypedQuery<Foo>('select fooProperty1 from Foo')`, it can just be inferred from `strongTypedQuery('select fooProperty1 from Foo')`, since `Foo` is already a valid type name. This would be awesome, and would automatically add types for all queries, especially in combination with the type generator project.
- Right now, `has` and `any` is not being validated. Can easily add this.
- Right now, the `Whitespace` string literal only accepts a single whitespace. So an arbitrary amount of whitespaces between for instance the property names is not allowed. This could be a problem with multiline etc. And adding more might impact the type checking performance.
- `and` and `or` is not supported in the `where` clause. This is easy to add, but only with a specific maximum amount of potential properties being selected (due to TypeScript not supporting recursive string literal types). There may be ways to work around this.
- The projection part can only contain one property. This is easy to fix, but only with a specific maximum amount of potential properties being selected (due to TypeScript not supporting recursive string literal types). There may be ways to work around this.
- Right now, date types are not supported, but again very easy to add and even validate.

# The code
Here's the code. Notice the `strongTypedQuery` function. That's where the magic happens. For every call to that, I've commented particular cases that the strong-typings catch.

```typescript
type Foo = {
    fooProperty1: string,
    fooProperty2: number,
    fooProperty3: boolean
}

type Bar = {
    barProperty1: string,
    barProperty2: number,
    barProperty3: boolean
}

interface EntityTypeMap {
    Foo: Foo,
    Bar: Bar
}


type EntityTypes = EntityTypeMap[keyof EntityTypeMap];

type EntityTypeProperty<TEntityType extends EntityTypes, TPropertyType> = { 
    [K in keyof TEntityType]: TEntityType[K] extends symbol ? 
        never : 
        TEntityType[K] extends TPropertyType ? 
            K :
            never
}[keyof TEntityType];

type EntityType<TEntityType extends EntityTypes> = keyof EntityTypeMap;


type Whitespace = ` `;

type OptionalWhitespace = Whitespace | "";


type Projections<TEntityType extends EntityTypes, TPropertyType> = 
    `${EntityTypeProperty<TEntityType, TPropertyType>}`;
    
type ProjectionPrefix<TEntityType extends EntityTypes> = 
    `select${Whitespace}${Projections<TEntityType>}${Whitespace}from${Whitespace}` |
    "";


type CriteriaOperator<T> = 
    T extends string ?
        (
            `${'='|'is'}` |
            `${'!='|'is_not'}` |
            `${'in'}` |
            `${'not_in'}` |
            `${'like'}` |
            `${'not_like'}`
        ) :
        T extends number ?
            (
                `${'='|'is'}` |
                `${'!='|'is_not'}` |
                `${'in'}` |
                `${'not_in'}` |
                `${'>'|'after'|'greater_than'}` |
                `${'<'|'before'|'less_than'}` |
                `${'>='}` |
                `${'<='}`
            ) :
            T extends boolean ?
                (
                    `${'='|'is'}` |
                    `${'!='|'is_not'}` |
                    `${'in'}` |
                    `${'not_in'}`
                ) :
                T extends Object ?
                    (
                        `${'has'}` |
                        `${'any'}`
                    ) :
                    never;

type CriteriaValue<T> = 
    T extends number ?
        `${number}` :
        T extends boolean ?
            `${boolean}` :
            T extends string ?
                `'${string}'` :
                never;

type CriteriaAndValue<TEntityType, TPropertyType> = 
    `${EntityTypeProperty<TEntityType, TPropertyType>}${Whitespace}${CriteriaOperator<TPropertyType>}${Whitespace}${CriteriaValue<TPropertyType>}`

type Criteria<TEntityType extends EntityTypes> = {
    [K in keyof TEntityType]: 
        `${CriteriaAndValue<TEntityType, TEntityType[K]>}`
}[keyof TEntityType];

type CriteriaSuffix<TEntityType extends EntityTypes> = 
    `${Whitespace}where${Whitespace}${Criteria<TEntityType>}` |
    ``;


type Query<TEntityType extends EntityTypes> = 
    `${ProjectionPrefix<TEntityType>}${EntityType<TEntityType>}${CriteriaSuffix<TEntityType>}`


function strongTypedQuery<TEntityType extends EntityTypes>(query: Query<TEntityType>) {
    return null!;
}


//valid, because "Foo" is a known type.
strongTypedQuery<Foo>("Foo");

//gives compile error, because "Blah" is not a valid type.
strongTypedQuery<Blah>("Blah");


//valid, because fooProperty1 exists on Foo
strongTypedQuery<Foo>("select fooProperty1 from Foo");

//gives compile error, because fooProperty1 does not exist on bar.
strongTypedQuery<Bar>("select fooProperty1 from Bar");


//valid, because fooProperty1 exists on Foo, and fooProperty1 is of type string.
strongTypedQuery<Foo>("Foo where fooProperty1 = 'abc'");

//gives compile error, because fooProperty1 is of type string, not number, so the value has to be wrapped in quotes.
strongTypedQuery<Foo>("Foo where fooProperty1 = 2388");

//gives compile error, because fooProperty1 is of type string, not boolean.
strongTypedQuery<Foo>("Foo where fooProperty1 = true");


//valid, because fooProperty2 is a number.
strongTypedQuery<Foo>("Foo where fooProperty2 = 24");

//gives compile error, because fooProperty2 is a number, not a string, so the value can't be wrapped in quotes.
strongTypedQuery<Foo>("Foo where fooProperty2 = 'abc'");

//gives compile error, because fooProperty2 is a number, not a boolean.
strongTypedQuery<Foo>("Foo where fooProperty2 = true");


//valid, because fooProperty3 is of type boolean.
strongTypedQuery<Foo>("Foo where fooProperty3 = false");

//gives compile error, because fooProperty3 is a boolean, so quotes are not allowed.
strongTypedQuery<Foo>("Foo where fooProperty3 = 'abc'");

//gives compile error, because fooProperty3 is a boolean, so numbers are not allowed.
strongTypedQuery<Foo>("Foo where fooProperty3 = 28");


//valid, because fooProperty1 exists on Foo, and fooProperty1 is of type string.
strongTypedQuery<Foo>("Foo where fooProperty1 = 'abc'");

//gives compile error, because fooProperty1 is a string, so the "<=" operator is not allowed.
strongTypedQuery<Foo>("Foo where fooProperty1 <= 'abc'");

//gives compile error, because fooProperty1 is a string, so the "has" operator is not allowed.
strongTypedQuery<Foo>("Foo where fooProperty1 <= 'abc'");


//long query syntax can also be used.
strongTypedQuery<Foo>("select fooProperty1 from Foo where fooProperty1 = 'abc'");
```

# Playground link
Play around with it [here](https://www.typescriptlang.org/play?#code/C4TwDgpgBAYg9nKBeKBvAUFLUBmCAKATnJIaAIwBcUAzsIQJYB2A5gDSbZ5xEkRkgATNSYBXALYAjfh2y4CxUqADM1SQgA2EAIZN0AX3TpQkKACFthZGk5ZJl3kpBVa9Zu1tR7hR-1DCoMSkZT29fAVUvTR09Q3RmYH4cbQBjaABRJmAGUAAVcAgAWW0wGzl4OGoK2WwLQmo6gyNjAqhM7LyCmmt2nJB8yGKwAG0AawgQOBw2rL6BopKAXQBuIxMM2c7IcNAAHlzeregIAA9EpgATbsP+rrYoXJ3byAA+a1QoT2GAaShmKHGk2mB02zwgi2oII6YJ+iygp3OV1oICkcA0UAA-J85HImBAAG78KDUTxyKFzAqw+FnCCXbqPRR+MGY7E4tm-SiktmBAn8AxjCZTB43eYrNatEUFfaS0wI2lImUQGhvFCAoWKoarcWmADqAAsckqwKloCgAAZQM1a9ZQADyYGycCY2g0+sNNGNaWsbsSHpNUAAPlAAETBrUtUy8ABWEBSjqYNGloPm1MR12TdweT3mKtZWDNABJUIqnknofN7gy+AIc-orZ4I9Bo7H40QIDgGCcyxTZTS6TNy11c54zTQIFo40WfUaTfoi824wwnYnyUcXnPUNO-Wl9DhiOIpwbfZ6IHXA55Q+GbQBhRiJRjae38bTAOCEfbDsmp+XdOiMViYlyWAABRATihaoAA5EgkEBpBDA0JBZ4BmBcgQZBACEMFwQhAD6TBwMASEWih3LgUW8FMMR55kWhFEEcAuHMNRpG0fmFEaAw4wsah2DoQxuGcdxdZgQAlMSYG5N+-ZBNIVgYrxIGKeRUHYfBiHIcpdFQVhsHqfhhE8WxbLocxmnGSpkECWZJFaXxFEvHp2g4PeeksIQOj3rhwB6roRkWfZUG7Hp0h4B5elaDQNDeb5VHmQF7FQS8MHxQl6G7ClZrKeJnIWVJcr9uoaIxIBCVKWVllqQh-kVYlmFVdFDE1bVplxbZtWBVZhFMW1dlYDlfUPNJSK2pIMZxqVHVQKBU2Wb5GntbNnW6CAxGDXIA2zXihKENarS3oaD4AGouqIEAftYnj5X2SKyUSClkRBd2EGeuXctdaZRMVuiTWxEFFVouivcpH0-q4-4sL9AVmpBRZ-u4+iQRab0Jdt-B7aYB33gw2gAIKXCdGhnd2RyVtmBSfoFJaMgIJNgmTNNrhuW4nhuWP8DjT6EC+b77OTrzM0eM47kW7PHad51Vk4tZZY2UBizjdMpgVCoZpAyrvF8vz-GqwKKhCeYqQreMExLSsFJWiqwuuWX6AKQLCmr4IY9AxsAMqiDgHZdquzIq+mg7q5TiUs7OADuer8BAh7uqzot3hz2jmwLi35vW2rQAAimdhAgMnxw3QHPZKsHlrzsQ42th53v5+uRaKrXbMJw+Hte52jey+gOCiEwi5OuDTosPMFzZ-wee+8rhcDsXyrAQAjjnIDUKPue1+JGByB5wCiIQTCBKIGgaBhqxxOgf6D8PK8gMBwYVMGomrOfrCX4vN91PfWpP0PBQj4vuwVC8G+Y4JzAHkDwRmzhcD7lgAgD+Z96AXx-lfXYdRAHBmAS2LwDgIHkCgXAcQ5hLBwPgcQZ+SC-4AJvhUKAEco5gKeLglAkFtCSBSJBOBX8X5jxQZYNBdQaGRw8lgnwODrDMNYewh+RhOHkO4ZQ2+CABF0O4E8QQ1gAC0ggAAsHCEFkMgL-bhqC36WCUUIsIEC1EoC0QADmITIgxyD5HUNoUIlREDlDWGSBoMcujSHf0cX-YxwZ+GuOgBY6sKhrD0DOvYvRASICGNXvIjBE13GRMgXufBMDEBhPoaIphLC2F+MQYEoxvCgHjkwREpwuCskENCYI8J2CMmMKgOI4pD8gA). Right now it gives an error in line 90, but it doesn't seem to be a valid error. I think it actually might be a bug in TypeScript.

**Comment by gismya** [comment]
This is super cool and absolutely crazy. I love it. I've spent the hour reading and processing it.

Could you elaborate more on what the goal for this is and what use cases you see?

I think some of the errors of the playground link might come from mixups between the `keyof EntityTypeMap` (That you call EntityTypes) and the `EntityTypeMap[keyof EntityTypeMap]` (That you call EntityTypes). In the type generator, we call them `EntityType` and `EntityData` to make them easier to distinguish from each other.

**Comment by gismya** [comment]
I also had some concerns and did some quick experiments in the same vein to flesh out my thinking. 
First of all I don't think TypeScript is designed for this kind of string parsing and has a high risk of leading to some of the issues you highlight in the limitations section. Specifically, I think that there is a high risk for performance problems and the brittleness might be a big issue.

Handling non-primitive types will also present issues. Mainly when using nested selects (Child.GrandChild), but there might be other issues as well.

The return values of the queries won't be more strongly typed than before. We will only validate that it's not an invalid query, but we still won't know if the API has the information to return or if the property will return empty.

A final problem is that the logic needed to get this to work will be too complicated which causes issues both with maintaining and also, for hypothetical future users, tracking back and parsing why they get the dreaded red squigglies will require really good code comments and would probably still take some effort.

All in all, I really like the idea and attempt but I have a hard time seeing that the practical applications (Unless I'm failing to imagine big practical uses) will be worth investing the time and effort that would be required to finalize this.

**Comment by ffMathy** [comment]
Thank you for chiming in.

I agree with your assessment. It makes a lot of sense, and makes me think the same.

The reason I'd be interested in this is due to us often changing our schema. We'd like to potentially catch errors in that regard that might happen at runtime.

But I think e2e tests are better suited for that at second glance.

Oh well, it was fun to experiment with! 😁

**Comment by gismya** [comment]
In individual projects, besides e2e tests, it could be a good idea to look into something like [Zod](https://zod.dev/?id=basic-usage) or [lizod](https://github.com/mizchi/lizod) for runtime validation of the results. It validates and strongly types the resulting data.

**Comment by ffMathy** [comment]
Thank you.

What about a builder pattern approach?

Something like:

```typescript
session.query(q => q
    .from(f => f.Foo)
    .withProjections(
        p => p.fooProperty1,
        p => p.fooProperty2,
        p => p.fooProperty3
    )
    .withCriteria(c => c
        .and(
            a => a
                .property(p => p.fooProperty1)
                .is("hello world"),
            a => a
                .property(p => p.fooProperty2)
                .lessThan(42),
            a => a
                .property(p => p.fooProperty2)
                .notIn([56, 57])
        )
    )
    .build()
)
```

We could strong-type it, and even retain backwards compatibility by checking if the query is `typeof` `"function"`.

You may be thinking "but wait, property names of non-classes (interfaces, types) are not available at runtime". But that's actually fixable:

https://www.npmjs.com/package/@fluffy-spoon/name-of

This package (under the hood) uses EcmaScript (and Node's) `Proxy` object (see more [here](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/Proxy) to infer names of types not available at runtime. Perfectly safe and stable.

Full code is here (look at how simple it is:

```typescript
function getPropertyNameInternal<T = unknown>(expression: (instance: T) => any, options: {
    isDeep: boolean
}) {
    let propertyThatWasAccessed = "";
    var proxy: any = new Proxy({} as any, {
        get: function(_: any, prop: any) {
            if(options.isDeep) {
                if(propertyThatWasAccessed)
                    propertyThatWasAccessed += ".";
                
                propertyThatWasAccessed += prop;
            } else {
                propertyThatWasAccessed = prop;
            }
            return proxy;
        }
    });
    expression(proxy);

    return propertyThatWasAccessed;
}

export function getPropertyName<T = unknown>(expression: (instance: T) => any) {
    return getPropertyNameInternal(expression, {
        isDeep: false
    });
}

export function getDeepPropertyName<T = unknown>(expression: (instance: T) => any) {
    return getPropertyNameInternal(expression, {
        isDeep: true
    });
}
```

And here's usage example:

```typescript
import { getPropertyName, getDeepPropertyName } from '@fluffy-spoon/name-of';

interface SomeType {
  foo: boolean;

  someNestedObject: {
      bar: string;
  }
}

console.log(getPropertyName<SomeType>(x => x.foo)); //prints "foo"
console.log(getPropertyName<SomeType>(x => x.someNestedObject)); //prints "someNestedObject"
console.log(getPropertyName<SomeType>(x => x.someNestedObject.bar)); //prints "bar"

console.log(getDeepPropertyName<SomeType>(x => x.foo)); //prints "foo"
console.log(getDeepPropertyName<SomeType>(x => x.someNestedObject)); //prints "someNestedObject"
console.log(getDeepPropertyName<SomeType>(x => x.someNestedObject.bar)); //prints "someNestedObject.bar"
```

**Comment by ffMathy** [comment]
It could also help alleviate #137 and therefore be an alternative to #139.

**Comment by ffMathy** [comment]
I tried making this in the playground. In my opinion, it works quite well.

[Here](https://www.typescriptlang.org/play?#code/C4TwDgpgBAysBOBLAdgcwEIFdEBsAmE8UAvFAN4BQU1UARtvgBQCUAXFAM4IqoDcFAXwoUUwQgDMAhgGNoAUWTBEoACrgIAWUlhyVGgDEA9ofZHDAGj3V0k+OxvxBw0RJnQzump25oz7Lkholl7ImAC2tIR+UKERhME0tMY4EJLI0UmGKWkJ1HiSYtEAIgUQuVCGtABWENLA0Q5OIoquslAOnjQBPA7+PqjlsZHwvTHhw+WZ2cijU6nI5flioyVi5ZU1daNmTRAAHmCG8MBQ0jiSHBxQAIqYhCBYuATwADwqCkqgUPtiyHhXG1qwAAfFBEGEwCkwhBFFc4IEMAxnp1qGAkAA3UpQNGGTZKQzIDiPfCEAD87AACvBcUDEASiUjCG8PsoQMD+F40YhMWJTkgxEhJMTnuSoABhfmERBCxmvd6KVns4SczC0HCIaSnekITB1I6MKxebEYrHwVJ4Ak4EBQUCQGAQFJ6uxQRgwz4gNSQLRgdgs1Tqb3MEig+Xuw1BshCQ1gVXqzUcB1AxjSSQ4HC0GQAa3YjHoT0IlOpeLphOFTNDiqDxFBVJpdRLDPzcr9bIjhq8iHEjGAAAtEBwAHQ44v0svwZjto3UXvUgDuMQg87k8Gp8EYACIxWkAOQnFNpziJuo22caiAD9fMfiT6jSbV0WUkBfz2sj0uy5kK0DAlgcqenVN0yzXNZSvZV-17fshyLWlR0fUg8xJeBr3-KAzWATB4GQG0+w4P9qCjFU1Q1KBZx7QgIGTQCM2kbMXUQ552AAeTCZQXglZQpRlJtP3dYFzCgdccUgY4QHXYEq1BdFDEQPA21Qztu1wgdpElQUxwnVCvBnQx52QRcoGXVcNy3ZBdwAg8yIok8zwvMCby1QkTgYwgn30+cOIFaUx14xVfwc-cgNokCm3s1DIMHVTOPU+CHybFD-3QzDsIi-CoEImgY2IzUGJYFEjRSE4AEc7nga1SHXdc0o7LsIugut8XfUL8tQkr7igABqUgAAME0dE4ABIyDq4dYKapCB1y5gBCgcRqTCKBuuqmgMqnNqys60hUAgYBaxE0AADlJGhJSoNtCB7X6o4wv-RS6qirzuKQ+StOodbrS6xbSPIs0oCG+61O82VJqRFgBCWhzVqNJKsKgd60qEKMzguK5PK4nyK2-MEIShN04X6Md8q5HloHO0V1zSPB1wAH3XI4qujE1eQe9HZQ4dgAEEV0kEB2MBp7nl878lWjWMSLvJz4F1YB9ReqcAeioGmyuUgAG0AF0EfA1Exc1SnGAHQ39jRCBLgbTnud5kKkPYNGYp4zHW2DcV+YxltgQklqaDu5TzrlrSdL0gyjP1ddt0p7cKiIbcjkjlNsMta1IgslI8AqZA2hE40GobOKJsvZaCO1o06vOp8Kb+BnwuUln7aQlXvgOM0zfpAcwm0Ki0xozNncoV7b3vFyiFIdyXcVgXy3d-z+7QnbkpT7vreeMDUIEFeVuLrK4yjg2jab02OHNqAufgHmXiXgsx8et2vyd6sr9Zh33c9vvbtq331H96u52fQyV1D8OfxI5HCgDHeAcc0jpytHQaAgUIBpwJJnVyo16z0jzs8Oyhd0rF20h-SA5d6ZYIVtfNmT5jbN0Pq3duYBO5BR7vfV+r0JZcHQa5EeBk7ZKyQkLNk09+4w2woFReQ915TjXlrUW2Vs77V5ioPahBvyun3i3ZAOY3SsnYI7SSUA5HUhkWwHR6g8DyNEkdaEnCJ7NlvgJXRhgZGgkYUaH2Z1P5e3lj2H+o8Q5rnXAATUMJgACZkTisT2KAiOAB6MBkdKZQG2vpU+OBpEKMQKbMEKVyKcGOtAFI6IHQVHEFASQcNSogEwZDByAVB6xVHiYw62SLFjiUSbFRAkIpBguEU5AIAiE11dmzIcmAOA9gvuOBKU4BGsOQoaKGW8SJTT6AiNxs8MKw2IY-euDkvBtw7kPZ2Q8QZPBYJpfuA4qgyWQIwbqf1hp4OgKSUkglKbrhmt1UR2Coxl09PAupIAzEQEaR+R2NjfmglIIaeEPRHwADIoCGkYLYmRjdfj-B0S2KApIHL6TyUQVgDlEUKOtD8GEqLuhoAxVsmgFINSZheL8-5gKn7WJ0aCgSlKpzrn7OuKA1NBL9gOoYYA3LqbsqNJy5AwrBLIEFQASQlTy0VXh1zqkzBASV65pXAAADKIFVeJKAeKZ4EtEsiklVwhiuUxTPLw1LaJ0r0YShl-SmXuhBQ60S-E4XWv-Jyjg6r+WCuFYqn1KB1WarlUG71HLUBmlKPAFQPY0jqpSJcBNSaFVRrFTG1IAo03ICYvAOQJVUzJoPnmgtRbMAltBIaqNxqvjEr+FcOYkCrWZqpTS+1djHUNOddw4FLL3XfjZe2kNfqeV8o4AKoVGbR1itDROjVsqJU1uDVOetRK9goquKse5a6tK2tpfS3t48b6usHd2j1I652oV9f6qdgbZ03o5Qu3lS7gARqfc+pVkhxACnVZEcQRw1Vfu-dQCmf7CAVuLTgADEAgNmmg1W2Dq6wMXqRY21FgJjxtrQ9QQ9XaZFOtPUClsbrL3Dq9Xhjlibx0iuoxytIYlUMMexYQeyZcZUcCYiJAoRx9CYAzo1HhNiABqqY7hgqo9QRgmIcB3E0eJ+TEBtGMv7e7a8nH828ZlvAATQmSwiZ0UpyTT54WGwHHJu47NjMSYgBrVTfbBaOxFmXHVqqeOED43pwTqDkBGZUCZiAYL4VWYgIpuzjmSMusVJp9QUAADisaBRaoPoQctOn+O+eEwOwLdmpOhbsxF5TUWSExe-HF-BAAJC4HNumedPrp-TfmAtBYK14ZpFCSw5iHrbJz5Y2ulY2c5wbzs1POY08IMuDXvNPkccgbJiyeDlG2sAW49wgs5m0WS1ATRkaXCgMe8x-WrHno3Q4yR29mE6idAaVCxNTTmkTo3FplDVEunUaATRLZtEbvKJyJm0BY0WmQNA2uXDGIPzrhN2+wJwzkFmYDiomX4Cihm7p8Z2JdZghs1x9HWWDMEgC6Cp8YXe4OTqpe2bpBHGoQW9Cdgd7-v-lW+tsqm2XTaJGmaMAthKJhZOWIzHXhJnrOh4QCRRFt4BuAOwPHKPms5bI+hwlUmycMIp8pKnum5uivp+FydAB9TV65mdTlZ6UjneV77c4gLzs0snIuQ2FzQUXfTotIUl5lbHKA5faa8017Lhncsk9IOri71coLa5ATTvXi2+USrN0aC3G2iuc+drb+3-Onerxd9QN3UFweWK9zrKR4b3tyvxz5wn-mQ9DrZKTuz5PI+Dmj8PZZIR4-vsN6GpPXgU-s7T9b0Eme+eO5K87nBru55rPd2Vz3MzN7Y9o+wGrHA6sgCr4r4PyvztkOUW95v-5rtTLchwk7bxQV8KnOQg+JZRk3XcVHlHuuZ768Z7R03oqB8gCt9o7qjAQ0ByU0a83Uk+DkBekUJ2JeWOUiTGq+tW9WCuQeROdeFGDepAt+KiR+U4J+ey7CHkF+521+RoWBb2D+eeOEz+AeMeHeNA7+Ty3SX+M8P+f+zsABQBwMIBzAYBueU++eM+GShe0Bi+l2JEKqBu7mEAW+KBteu+oeUA4eyylOL+seb+XeEhzB-crBQ+XOykJsWe4+dwguRoAglBkBKkIhXgsy2OmqUh7AUhMhNexO9eauTeGuLeA4ber+-cDB3emhfeNAOhymW2Ge+hPOY+Au4BqEFhReY4MBcymo2acaea7ASWOahAqWlw6Wia-ujWBOLWaB9ijeymOBJcWuqhdB1AfhyRAohuvYSagR1AwRCm6eNu4RdukROe-4Zh-BKy88YuEOEuohUu4hZauRaRyWmRaW8auRThhR8hrhJRdwZRuC1B+R7etO-4fhKaHA9RuRWhr0LRBuw+VBg4BhXRE+fBEBghZxlhHuzwCR2Ov6AokxGR8AWRCYsxaQ8xSuzKe+Ye7hEeiUtxdUtRORaQRhKmTxUigGwGbxcanxEJeR3m2+qBix6BbhpRHhIJqyQhg4uxeaUJ7yNhUi4J3x+ahaMGCJKWMxGWNB1eCx-xChShWx04FRDJPhr0fhwIxAhxWkxxoR7RUEFxDuUR1xMRoJc+w2wx1hS+UihJcxVJyGNJ0x2RFJvxO+zJSxgJ2JwJT+relRbJRofhLwfJTRcSO0bOv+uhYRIpERYp3RQufRsRVhG8YheskG8ASGqYqpHxdJcxyBzhRRquyx0AOJEyUpUE5J5aypqYxJMJ28cJiGcZOAfpSJGpQZTJZ2LJQJyyFhipPxqZCZIx3usJoMX83sXYAAhCoQySYd-LpL-N4huAKsjpyRwJANIJ2KkggthMJISuUlUk5MkqYtkk+KtkdpRHVGQSWO8iLrcd1ENAOWOdCDNP9ByRsQOPruubcusd5gOMcWDBDHKYaBEgAFTnntjnmHYOlpLFJk4cCGBggnD9jZxiB1DwJFKoCSAoAsIoBvhFLADABZiDjXkRKMzchYiinZ4hFdIgCVnUB3TqCGCFLq7EAVQ7aXhVH9GwzdTbhDRhYDg87nCyCMBRIRIDCgIAA624240024J5PR3wOACYYIXYZOf5IFGcEAqFUAu6iF0MtxRFMsMqMATEkKaAJBp5kpeJihdmWsSM5wB2r4Y0jY6mt8pqTaFQ1QQI+pxoUFvIwOz2K59S0INmO2GsmOiRjkAQ0sssyh4R6B-yDcVlpZpe28plsiV+s5BIait832t8v2vygl3Ozl2S5xQyIyk59e-ynWd+BIzA850+clqU7lsBSZFZ+ZUZ5xsVEVZyFyjA24Ak9Filwg4gshlpu0eV0IbwZ+OKP4vl72jAXFaQsgmi2iTG-shUo5qgiawAAA6rVtILINkWnBVFXDQJiEQDiHsCAOwExmfi+NSHNYwJGEUlcExgJMaatuwBVTXowIbgtd0gJMJMdQhThYpF5WmoNcNaNQmHJPutdf1UNeviNWlmnJ9OuBeFgl4KKs9QUK9RzO9WNZtNIr9SlfPLNT0hUtYe8k1YwNDY-rhf2fXjdUDSDQ9fwEjPeO9EtTcKUk0mEvfHsAOA4CYQOH1EmMTaCHsA5PVDIowDTVAKTS2jMLYA2TQAzYSkzc7KTUsBAOTRTVZA7szXTahAOPrKKmLdzaJIjc7GANueMIQOTQOP2IwAACwABMzAFpYt+6stoA8t98it2GwA5NBttGvNJN+62yXl1ttNlN-QZgnN3qatHAG4XAmA4g4gl4rtUASVhohyTA9kESESeNb50qs4eKYdVNx4bNDgAkAtHQc0hgC0HQIt0AFqIwtgOOUA2tXSCCulWwudtGLoO2Hgb524XtPt9FQAA) is the link.

**Comment by jimmycallin** [comment]
as @gismya mentioned in the PR, this is cool but not within the scope of the api client

**Comment by ffMathy** [comment]
Yeah. Good call on cleaning it up.
