### ISSUE TITLE
Issue after 1.8.0: window is not defined

### ISSUE THREAD

**Issue by ffMathy** [ftrackhq/ftrack-javascript#147]
We get this error:
![MicrosoftTeams-image (7)](https://github.com/ftrackhq/ftrack-javascript/assets/2824010/ae44bc67-6b8a-48a4-80d5-a49dbe072b26)

I suppose the cause is the reconnect behavior. `window` is not available in Node.

**Comment by gismya** [comment]
What was an oversight, will get that fixed.

Long term the tests should be configured to check for compatibility with node and browsers, not just browsers as it's configured right now.

**Comment by ffMathy** [comment]
Yeah no worries, and no rush. We're just happy of this amazing work. And yes, should only happen for node, and even only for users of the event hub which has not been supported before.
