### ISSUE TITLE
Benefits of `session.call`?

### ISSUE THREAD

**Issue by ffMathy** [ftrackhq/ftrack-javascript#149]
What are the benefits of `session.call` versus running individual queries in parallel? Is it faster?

Perhaps this could be added to the documentation?

**Comment by gismya** [comment]
I can't tell you the difference on a database level, but I suspect there are differences there as well, but from the perspective of using the API, it allows the user to make queries that are dependent on each other. For example, if you're moving a task outside of the project dates, updating the project dates and the task dates in parallel would make the task update fail if it happened before the project date update.

**Comment by ffMathy** [comment]
Thanks for sharing some more. Let's leave this issue open as a reminder to add documentation detailing this. I may do that if I get the time anytime soon.

**Comment by ffMathy** [comment]
Just to be sure. So if I nest multiple calls in one, and one of them fails, then all of them fails?

So like a transaction?

**Comment by gismya** [comment]
Yes

**Comment by ffMathy** [comment]
Interesting. What if I want to create a new entity and add custom attributes to it, but as an atomic operation. How can I do that?

Because adding the custom attribute requires the entity ID, which is not known yet. Is there a trick there that can be used? Or does that then have to be two separate operations?

**Comment by gismya** [comment]
Generate a UUID yourself and use that for the created entity.

**Comment by ffMathy** [comment]
Aha - did not know that Ftrack allowed for specifying custom UUIDs. Thanks!

**Comment by jimmycallin** [comment]
Closing this as resolved.
