### ISSUE TITLE
Modifying types via the API?

### ISSUE THREAD

**Issue by ffMathy** [ftrackhq/ftrack-javascript#151]
We found this post from 2018: https://forum.ftrack.com/topic/1325-how-to-create-new-entity-types-with-python-api/

Back then, it was not possible. Is it possible now? Inside the API reference, we see types such as:

- `CustomAttributeType`
- `Type`
- etc

Can I add new ones of these via the API?

If not, that's something we'd really like to request. We have multiple Ftrack environments, and would like to keep them in sync. It is our number one source of error today when we go from staging to production.

Ideally we're trying to make some kind of "migration script" framework where we (as part of a feature branch) can have code that adds new custom attributes or types as needed, and then (in that way) keeps it in sync.

**Comment by ffMathy** [comment]
If I try the following code:

```typescript
await session.create("Type", {
  color: "#ffffff",
  is_billable: false,
  name: "mathias",
  sort: 1,
  task_type_schemas: [],
  tasks: []
})
```

I get the following error:

> ServerPermissionDeniedError: Permission denied: not allowed to 'create' 'TaskType'. Missing the required 'Manage settings' permission.

This could indicate that some logic is there for doing this, but how do I grant myself permission to do so?

**Comment by ffMathy** [comment]
Similarly, if I do:

```typescript
await session.create("CustomAttributeType", {
  core: false,
  name: "mathias"
})
```

I get the error:

> ServerPermissionDeniedError: Permission denied: not allowed to 'create' 'CustomAttributeType'. Operation 'create' can never be done on 'CustomAttributeType'.

That one seems a bit more impossible.

**Comment by gismya** [comment]
It is possible to add custom attribute types. But I think there might be discrepancies in naming. What you call CustomAttributeType is a CustomAttributeConfiguration in the API. A CustomAttributeType are the base primitive types, "Boolean", "Text" etc. Which I understand is confusing, we call the (Final) types Custom Attribute Type internally as well.

The The Python Client has documentation detailing how to do it: https://ftrack-python-api.readthedocs.io/en/stable/example/manage_custom_attribute_configuration.html

Besides the normal differences in how the clients work (i.e you don't commit the changes), the queries involved should be the same. Please report if there's anything that doesn't work..

**Comment by ffMathy** [comment]
That's great news! What about the types?

**Comment by gismya** [comment]
They are also available, and your example code works when I try it. Make sure the API key you are using have the needed permissions.

**Comment by gismya** [comment]
<img width="927" alt="image" src="https://github.com/ftrackhq/ftrack-javascript/assets/8929526/fff17ed9-8533-48a1-863d-fb54b373cfe9">

**Comment by ffMathy** [comment]
Thanks a lot! All of the information you are giving me here, I will add that to the documentation at some point.

What about "Objects"? How do I add those? I tried the type `ObjectType`, but then I get:
> [ServerPermissionDeniedError]: Permission denied: not allowed to 'create' 'ObjectType'. Operation 'create' can never be done on 'ObjectType'.

**Comment by gismya** [comment]
This is deeper into the stack than what the API Client is concerned about, and also things I, unfortunately, don't know without investigating. I think they are not supposed to be added to, but I can't tell you exactly.

The documentation I know that concerns this is: https://ftrack-python-api.readthedocs.io/en/stable/example/workflow_schema.html?highlight=ObjectType#creating-workflow-schemas and https://ftrack-python-api.readthedocs.io/en/stable/example/manage_custom_attribute_configuration.html?highlight=ObjectType#entity-types

If that does not answer the questions you have send an email to support.

**Comment by ffMathy** [comment]
Thank you! I wrote to support.

Let's leave this issue open in the meanwhile. That way, I can also contribute to the documentation whenever I get the chance.

**Comment by jimmycallin** [comment]
Hi @ffMathy, is this resolved and ready to be closed? 

We have btw moved the documentation over to our new developer hub: https://developer.ftrack.com/api-clients/examples/workflow-schema

It is currently not open to external contributors, but we are working towards making it the case. In the meantime, if you have any ideas on how to help improve the documentation, you can email to support.

**Comment by ffMathy** [comment]
Very interesting!

I still have not contributed to the documentation on this. I do plan on doing so, and I was thinking of leaving the issue open to track it. But it's not a big deal if it is closed, I am just afraid I'll forget.

Because we found out how to modify all of this. I just need to contribute it back.

**Comment by jimmycallin** [comment]
I have added a tracking issue internally for improving  the documentation, so we'll get to it eventually :) I'll close this for now then. Thanks!
