### ISSUE TITLE
Can't query CustomAttributeType

### ISSUE THREAD

**Issue by ffMathy** [ftrackhq/ftrack-javascript#152]
I am trying the following:

```typescript
await session.query("CustomAttributeType where name is 'text'")
```

And I get the following error:

> CustomError [ServerError]: Failed to parse: CustomAttributeType where name is 'text'. need more than 1 value to unpack

I tried to look for this error in the code, but it looks like it comes from the server side. So I am unsure on how to contribute, but would love to.

**Comment by gismya** [comment]
It still need what properties you want to get from the CustomAttributeType. We don't support getting all properties directly.
`await session.query("Select name from CustomAttributeType where name is 'text'")` for example would work.

To get all the properties, if we don't want to specify them one by one (This should probably only be done while testing, and not in production), you could do something like:

```
let entityType = "CustomAttributeType";

let properties = session.schemaMapping[entityType].properties;

let allProps = Object.keys(properties).reduce((result, name) => {
  if (properties[name].type !== "array") {
    result.push(name);
  }
  return result;
}, []);

session
  .query(`select ${allProps.join(", ")} from ${entityType} limit 1`)
  .then((result) => console.table(Object.entries(result.data[0])));
```

**Comment by ffMathy** [comment]
Thank you!

**Comment by ffMathy** [comment]
I haven't had the time to look into the documentation, but I think I'm going to do it as part of official custom attribute support in the API.
