### ISSUE TITLE
Custom attributes are not working

### ISSUE THREAD

**Issue by ffMathy** [ftrackhq/ftrack-javascript#153]
Originally, we wanted to update custom attributes of my entity.

We tried the following:

```typescript
entity.custom_attributes.push({
      key,
      value: value instanceof Date
        ? value.toISOString()
        : value,
    });
```

Only to realize that it doesn't look like this is supported.

We then stumbled upon an old forum post: https://forum.ftrack.com/topic/1293-update-custom-attribute-via-javascript-api/

It still contains the solution it seems. But I think we should officially support attributes, or at least document how these are updated.

**Comment by ffMathy** [comment]
For reference, here's a method that works.

```typescript
  public async upsertCustomAttribute<TModel extends Pick<TypedContext, 'custom_attributes' | 'id'>>(
    entity: TModel,
    key: string,
    value: string | number | boolean | string[] | Date | undefined,
  ) {
    if (!entity?.id) {
      throw new Error('Can\'t upsert custom attribute of missing entity, or an entity without an ID');
    }

    if (!entity.custom_attributes) {
      throw new Error("Can't upsert custom attribute of entity when the existing custom attributes have not been fetched");
    }

    const customAttribute = entity.custom_attributes.find(x => x.key === key);
    if (!customAttribute) {
      throw new Error(`The custom attribute ${key} does not exist. Did you forget to create that custom attribute in Ftrack's settings?`);
    }

    const configurationId = customAttribute.configuration_id;
    if (!configurationId) {
      throw new Error(`The custom attribute ${key} does not have a configuration ID. Did you forget to create that custom attribute in Ftrack's settings?`);
    }

    const newValue = value instanceof Date
      ? value.toISOString()
      : value;

    const session = await this.createFtrackSession();
    await session.update<ContextCustomAttributeValue>(
      'ContextCustomAttributeValue',
      [configurationId, entity.id],
      {
        value: newValue,
        key,
        entity_id: entity.id,
        configuration_id: configurationId,
      },
    );
  }
```

**Comment by jimmycallin** [comment]
Hi!

The documentation for custom attributes have moved here: https://developer.ftrack.com/api-clients/examples/custom-attribute

We are tracking updates to how to work with custom attributes with the javascript api in that (currently internal) repository. So I will be closing this issue. Thanks for your feedback!

**Comment by ffMathy** [comment]
What will happen to the documentation in this repo then? Thinking of the README.md file.

**Comment by jimmycallin** [comment]
> What will happen to the documentation in this repo then? Thinking of the README.md file.

The purpose of the README is to be a basic overview of the API client or highly technical and specific documentation, and refer to the developer hub to any deeper conceptual documentation.

For instance, working with custom attributes belongs in the developer hub, while how to integrate ts-schema-generator and the api client probably belongs here.

**Comment by ffMathy** [comment]
Ah, that makes total sense. Looking forward to being able to contribute to the developer hub too. From the initial looks, it looks nice.
