### ISSUE TITLE
Issue after 1.8.1: window is not defined

### ISSUE THREAD

**Issue by stefanalexandru02** [ftrackhq/ftrack-javascript#154]
![image](https://github.com/ftrackhq/ftrack-javascript/assets/46138368/6efe3884-64f9-4235-b452-d113e451b320)

Hi, we are getting this error while running the application using Node and Jest (as part of integration testing).

It's not consistently happening, and manually running that particular test again seems to get rid of it. Maybe it could be related to increased load or something?

I see a similar issue was closed on 1.8.0, currently we are using 1.8.1 version

**Comment by gismya** [comment]
Thank you for the report! Indeed it's the same issue that I thought I had solved for 1.8.1 release, but now I see that the fix only fixed a subset of the issues.  I've made a fix that should be released shortly.

**Comment by gismya** [comment]
Only not yet having spent the time to analyze potential issues with that.

**Comment by gismya** [comment]
@stefanalexandru02 - a fix for this is now released

**Comment by ffMathy** [comment]
That's fair enough ❤️ Thanks for the speedy fix!

_By the way, @stefanalexandru02 and I are on the same team :smirk:_

As you can probably tell, we are starting to use the Ftrack JavaScript API more and more. It's great to see the progress on it!
