### ISSUE TITLE
Events with the same ID are being received twice

### ISSUE THREAD

**Issue by ffMathy** [ftrackhq/ftrack-javascript#163]
We are encountering an issue where sometimes, events with the same ID are being received twice.

The events are being published via `publishAndWaitForReply`. We are not sure if the event is always received twice, or only sometimes. We also do not know if it's due to a race condition.

Is this known behavior? What are your thoughts?

**Comment by ffMathy** [comment]
It's important to emphasize that it could also be the publish method publishing the event twice. We're not fully sure, but there's definitely a bug there somewhere.

**Comment by gismya** [comment]
If you give me a reproducible example I will take a look at it.

**Comment by ffMathy** [comment]
> If you give me a reproducible example I will take a look at it. 

Sure thing! I think I can have that ready next week.

**Comment by ffMathy** [comment]
Here's a simple repro:

```typescript
async function createFtrackEventSession() {
  const session = await createFtrackSession();

  session.eventHub.connect();

  const signal = AbortSignal.timeout(10_000);
  while (!session.eventHub.isConnected && !signal.aborted) {
    await delay(10);
  }

  if (signal.aborted) {
    throw new Error('Could not connect to the Event Hub within the timeout.');
  }

  return session;
}

test.only('Event hub receives event twice', async () => {
  const session = await createFtrackEventSession();

  const events = new Set<EventPayload>();
  await session.eventHub.subscribe('topic=*', e => {
    events.add(e);
    return { reply: 'hi!' };
  });

  await session.eventHub.publishAndWaitForReply(
    new Event('wats.test', {}),
    { timeout: 10_000 },
  ) as any;
  expect(events.size).toBe(1);
});
```

Here, for me, `events.size` is *always* `2` instead of 1.

**Comment by gismya** [comment]
Your test code is picking up the reply that the subscription is sending in return - it's endlessly sending itself "hi!" as a reply to itself.

**Comment by ffMathy** [comment]
Yes, but shouldn't the size then be `1`? Where is the other event coming from?

**Comment by ffMathy** [comment]
Aaaah, I see. That's probably

**Comment by ffMathy** [comment]
Also, it seems the ID of the events are the same?

**Comment by gismya** [comment]
> How do I detect if something is a reply?
It has the topic `ftrack.meta.reply` and a inReplyToEvent is not `null`

> Also, it seems the ID of the events are the same?
Not in my tests
<img width="825" alt="image" src="https://github.com/ftrackhq/ftrack-javascript/assets/8929526/7f59c7c3-e3a7-4e46-a8da-d7b99b022275">


> Also, would be awesome if this was clarified in the documentation. When people subscribe to events, I don't think they want to subscribe to replies.
Usually applications subscribe to specific topics.

> Does the Python client also do this?
For this, the subscription parsing should work the same. There are some more advanced topic parsing available in the python client that is absent from the JavaScript client.

> To me, the replies functionality should be internal behavior somehow.
Replies is just another event, but with specified syntax. But that could definitely be expanded upon in the documentation.

**Comment by ffMathy** [comment]
Thank you for the update!

Ah yes. That was based on what we saw in production, but perhaps that was because  didn't have a `inReplyToEvent` check. 

I guess I need to extend my tests so they spam events a bit more.

But before I do that, I have one question. Can replies to events also have the same ID as the event itself?

**Comment by gismya** [comment]
If two events ever have the same ID, no matter if they are replies or not, that is a major bug and really needs to be investigated. All events created with the Event Constructor have a randomly generated UUID.

**Comment by gismya** [comment]
The same event might be handled multiple times (Multiple subscribers might handle it), but each event should have a unique ID.

**Comment by ffMathy** [comment]
Yeah okay.

It only happens rarely, but after all this, I suspect the error might be on our side. I'll reopen when I know more. Sorry for the inconvenience.

**Comment by ffMathy** [comment]
This is happening again. We are trying a better repro.

**Comment by stefanalexandru02** [comment]
We were able to reproduce the issue, with random number of events coming through using this test format:

```javascript
test.only('Event hub receives event once', async () => {
  const session = await createFtrackEventSession();
  // await createFtrackEventSession();
  // await createFtrackEventSession();
  // await createFtrackEventSession();
  const events = new Array<EventPayload>();
  session.eventHub.subscribe('topic=*', async e => {
    if (e.inReplyToEvent) {
      return;
    }
    console.log('event received', e);
    if (events.some(x => x.id === e.id)) {
      throw new Error(`Event received twice: ${e.id}`);
    }
    events.push(e);
    await session.eventHub.publishReply(e, {});
  });
  // const promises = [
  //   session.eventHub.publishAndWaitForReply(
  //     new Event(`wats.test${uuidv4()}`, {}),
  //     { timeout: 10_000 },
  //   ) as any,
  // ];
  // await Promise.all(promises);
  await session.eventHub.publish(
    new Event(`wats.test${uuidv4()}`, {}),
    { timeout: 10_000 },
  ) as any;

  await delay(5_000);
  console.log(events);
  await delay(5_000);
});
``` 

When running the test, the same event is received multiple times, with the exact same payload:
![image](https://github.com/ftrackhq/ftrack-javascript/assets/46138368/65458466-5ea4-42dd-af9f-6169c16b7770)

**Comment by gismya** [comment]
Thank you. I'll look into it.

**Comment by stefanalexandru02** [comment]
Thanks

**Comment by ffMathy** [comment]
And here are the relevant functions we use for connecting.

```typescript
let ftrackSessionPromise: Promise<Session> | undefined;

export async function createFtrackSession() {
  if (ftrackSessionPromise) {
    return ftrackSessionPromise;
  }

  async function createSession() {
    const credentials = ftrackWidget.getCredentials();

    const ftrackApiKey = credentials?.apiKey || await getParameterStoreValue('/ftrack/api-key');
    const ftrackServerUrl = credentials?.serverUrl || await getParameterStoreValue('/ftrack/server-url');
    const ftrackApiUser = credentials?.apiUser || await getParameterStoreValue('/ftrack/api-user');

    const session = new Session(
      ftrackServerUrl!,
      ftrackApiUser!,
      ftrackApiKey!,
    );

    return session;
  }

  ftrackSessionPromise = createSession();
  return ftrackSessionPromise;
}

export async function createFtrackEventSession() {
  const session = await createFtrackSession();

  session.eventHub.connect();

  const signal = AbortSignal.timeout(10_000);
  while (!session.eventHub.isConnected && !signal.aborted) {
    await delay(10);
  }

  if (signal.aborted) {
    throw new Error('Could not connect to the Event Hub within the timeout.');
  }

  return session;
}
```

Not sure if they can be the cause of it too, so here they are.

**Comment by gismya** [comment]
When I try to replicate it it still looks like it's an issue of multiple subscribers being registered, not multiple events being sent. If you add the UUID to the console log in the subscriber and in the final event console log you can more easily see that behaviour.
![image](https://github.com/ftrackhq/ftrack-javascript/assets/8929526/02f10875-9447-40d4-a832-b60655a8f39f)


```
test.only('Event hub receives event once', async () => {
  const session = await createFtrackEventSession();
  const uuid = uuidv4();
  // await createFtrackEventSession();
  // await createFtrackEventSession();
  // await createFtrackEventSession();
  const events = new Array<EventPayload>();
  session.eventHub.subscribe('topic=*', async e => {
    if (e.inReplyToEvent) {
      return;
    }
    console.log('event received', uuid, e);
    if (events.some(x => x.id === e.id)) {
      throw new Error(`Event received twice: ${e.id}`);
    }
    events.push(e);
    await session.eventHub.publishReply(e, {});
  });
  // const promises = [
  //   session.eventHub.publishAndWaitForReply(
  //     new Event(`wats.test${uuidv4()}`, {}),
  //     { timeout: 10_000 },
  //   ) as any,
  // ];
  // await Promise.all(promises);
  await session.eventHub.publish(
    new Event(`wats.test${uuid}`, {}),
    { timeout: 10_000 },
  ) as any;

  await delay(5_000);
  console.log(uuid, events);
  await delay(5_000);
});
```

**Comment by gismya** [comment]
I don't know, sorry. But from the samples I've seen so far this does not look like a bug in the API Client.

**Comment by ffMathy** [comment]
Interesting. We'll see if we can dive more into the way we run the tests. Perhaps try it on brand new setups or something. Will re-open if relevant.

Sorry for all the ups and downs on this rollercoaster-type issue 😆
