### ISSUE TITLE
Catch error 502

### ISSUE THREAD

**Issue by ffMathy** [ftrackhq/ftrack-javascript#165]
When ftrack is overloaded, it returns a status code 502 with HTML content.

The client throws this as a json decode issue.

Would be nice if it threw a specific error, so it would be easier to implement retry behavior.

Another thing I've been wondering is if the event hub will also reconnect if ftrack got overloaded and it disconnected?

**Comment by gismya** [comment]
I'll forward this to the platform team, there's ongoing work for more consistent and useful error codes and messages. An upcoming feature is also a global event queue that can tell a subscribed client if there are events that the client hasn't received that will be helpful for these scenarios.

The event hub will try to reconnect after any kind of disconnection unless it's an explicit call from the client to disconnect. The latest release also attempts to reconnect on every emit if the WebSocket client is not connected. If you find any case where that doesn't work, please report it and we'll investigate.

**Comment by ffMathy** [comment]
Thank you! Sounds great!
