### ISSUE TITLE
Unknown error

### ISSUE THREAD

**Issue by ffMathy** [ftrackhq/ftrack-javascript#178]
I get the following error when I debug my tests locally and have various breakpoints set. Maybe a breakpoint is causing the something to disconnect? This was revealed after applying #176 was applied locally.

The weird part though is that I am actually not using the event hub. I may be connected to it though, but the error occurs in a call to `session.call`, as the stack also reveals.

```
Error: Unknown error: {\"cause\":{\"errno\":-32,\"code\":\"EPIPE\",\"syscall\":\"write\"}}
    at Session.call (/workspaces/WATS/node_modules/.pnpm/@ftrack+api@1.8.3_ws@8.14.2/node_modules/@ftrack/api/source/session.ts:621:15)
    at async Session.update (/workspaces/WATS/node_modules/.pnpm/@ftrack+api@1.8.3_ws@8.14.2/node_modules/@ftrack/api/source/session.ts:894:23)
```

**Comment by gismya** [comment]
`Session.call` doesn't have anything to do with the event hub. It's the method that is responsible for sending the command when using the session methods. `Update`, `Query`, `Create` and `Ensure` all just setup the operation that is sent with `Call`.

Sounds like the ftrack backend times out while you're debugging.

**Comment by ffMathy** [comment]
Well, the weird part of it is that the breakpoint is on a session.call call. And then when I continue (so it executes the call), it fails.

Very strange behavior.

**Comment by gismya** [comment]
Don't think it's related to the Javascript client. I'll close this for now.

**Comment by ffMathy** [comment]
Fair enough, I guess without a repro it's difficult.
