### ISSUE TITLE
ServerError: 'NoneType' object has no attribute 'add'

### ISSUE THREAD

**Issue by ffMathy** [ftrackhq/ftrack-javascript#179]
I am trying to upsert (insert or update) a custom attribute value for an entity.

It fails with the error:

> Failed to perform request.  CustomError [ServerError]: 'NoneType' object has no attribute 'add'
>     at Session.getErrorFromResponse (/workspaces/WATS/node_modules/.pnpm/@ftrack+api@1.8.3_ws@8.14.2/node_modules/@ftrack/api/source/session.ts:344:19)
>     at Session.call (/workspaces/WATS/node_modules/.pnpm/@ftrack+api@1.8.3_ws@8.14.2/node_modules/@ftrack/api/source/session.ts:627:20)
>     at processTicksAndRejections (node:internal/process/task_queues:95:5)
>     at Session.create (/workspaces/WATS/node_modules/.pnpm/@ftrack+api@1.8.3_ws@8.14.2/node_modules/@ftrack/api/source/session.ts:867:23)
>     at upsertCustomAttribute (/workspaces/WATS/src/libs/@wats-common/src/infrastructure/ftrack/session.ts:164:5)
>     at SkuBuilder.addCustomAttribute (/workspaces/WATS/src/libs/@wats-common/src/domain/builders/Builder.ts:16:5)
>     at SkuBuilder.build (/workspaces/WATS/src/libs/@wats-common/src/domain/builders/SkuBuilder.ts:114:5)
>     at setupTasks (/workspaces/WATS/src/apps/ftrack-event-lambda/src/domain/actions/EqualizeDatesAction.test.ts:56:18)
>     at /workspaces/WATS/src/apps/ftrack-event-lambda/src/domain/actions/EqualizeDatesAction.test.ts:33:11 {
>   errorCode: null
> }

Code:
```typescript
  const existingValue = await new QueryBuilder(x => x.CustomAttributeValue)
    .select(x => x.property('entity_id'))
    .where(x => x
      .property('configuration_id').is(configurationId!)
      .property('entity_id').is(entity.id!))
    .getOneOrNull();
  if (existingValue) {
    await session.update<ContextCustomAttributeValue>(
      'ContextCustomAttributeValue',
      [configurationId, entity.id],
      {
        value: newValue,
      },
    );
  } else {
    await session.create<ContextCustomAttributeValue>(
      'ContextCustomAttributeValue',
      {
        value: newValue,
        key: configurationId,
        configuration_id: configurationId,
        entity_id: entity.id,
      },
    );
  }
```

The query builder is our own abstraction, but really it just checks if it exists or not already. It's the `session.create` call that fails.

**Comment by ffMathy** [comment]
Related: #153

**Comment by gismya** [comment]
It's an issue from the server, not the API client. Please send an email to support at support@ftrack.com and they'll get this to the correct people.
