### ISSUE TITLE
Integrating TS schema generator into this library

### ISSUE THREAD

**Issue by ffMathy** [ftrackhq/ftrack-javascript#188]
The discussion over at https://github.com/ftrackhq/ftrack-ts-schema-generator/issues/29 had me thinking...

What if the TS schema generator was actually not a separate repo, but instead merged into this one?

Before you call me crazy on this (because I know how it sounds), hear me out. The following are my thoughts. 

We could use an NPM binary definition (see https://stackoverflow.com/questions/53571669/is-it-possible-to-run-multiple-binaries-from-a-single-module-via-npx), which would allow us to not make the default entry point runnable, yet still point to an entrypoint Javascript file.

1. Doing the above would not make the bundle size bigger, due to tree shaking. The "main" of the package would still point to the same Javascript file, making the library behave the same when imported as, well, a library.
2. It actually would feel kind of natural as a consumer if the client. You download a client library, and it has features to also generate types, but as a binary. 
3. It would keep the documentation gathered in one place.
4. It would make it easier to make tests that make sure everything plays well together, avoiding conflicts with type names etc. 
5. It would make it easier to make types extendable as defined in my other issue.
6. It would make it easier to bundle upstream changes together.
7. It would make it harder to introduce downstream bugs due to upstream changes.
8. It would feel more monorepo-ish. Same ci/cd configuration needed etc.

**Comment by gismya** [comment]
I have no issue with the suggestion itself, but for now, I don't think the upsides justify the time investment it would require for it to be more than two disjointed code bases sharing the same repository.

**Comment by jimmycallin** [comment]
As @gismya mentioned, we have no plans on integrating them for now. This might change in the future, but for now we are keeping our public npm projects (@ftrack/web-widget, @ftrack/ts-schema-generator, @ftrack/api) in separate repositories.
