### ISSUE TITLE
How do we enable logging?

### ISSUE THREAD

**Issue by ffMathy** [ftrackhq/ftrack-javascript#195]
I see that Ftrack references a `loglevel` logger.

How can I make these log messages appear? Currently, nothing comes out.

Would it make sense to make the logger configurable from the outside?

**Comment by gismya** [comment]
It uses the [loglevel](https://www.npmjs.com/package/loglevel) package.

As such you would use 

```
import loglevel from "loglevel";
const logger = loglevel.getLogger("ftrack_api");
logger.setLevel("DEBUG"); // Or the log level you want to see
```

Or if you want to enable the logging for the event server that would be

```
import loglevel from "loglevel";
const logger = loglevel.getLogger("ftrack_api:EventHub");
logger.setLevel("DEBUG"); // Or the log level you want to see
```

**Comment by ffMathy** [comment]
Ah. That's pretty brilliant. Thanks!
