### ISSUE TITLE
Setting metadata from the API?

### ISSUE THREAD

**Issue by ffMathy** [ftrackhq/ftrack-javascript#218]
How do I set metadata from the API?

We currently know how to do it for custom attributes, but not metadata.

**Comment by gismya** [comment]
The easiest way would be to use `Session.ensure()`

```
Session.ensure(
  "Metadata",
  {
    key: "foo", // The metadata key
    value: "bar", // The metadata value
    parent_id: "e8925613-d74c-4faf-a654-99352ffb2632", // The entity that should contain the metadata
    parent_type: "Task", // The type of the entity
  },
  ["key", "parent_id"] // The primary key is a composite of the key and parent_id
);
```

![image](https://github.com/ftrackhq/ftrack-javascript/assets/8929526/6ce5128d-3766-4818-af75-19e9e7bf2672)

**Comment by ffMathy** [comment]
Shouldn't we have a method for doing this on the API client?

Or perhaps the API client for JavaScript is meant to be more low-level.

**Comment by gismya** [comment]
So far, the strategy for the JavaScript client has been to keep it a thin client.
