### ISSUE TITLE
Method to explicitly disconnect event hub

### ISSUE THREAD

**Issue by ffMathy** [ftrackhq/ftrack-javascript#238]
Is this possible? We are running out of socket connections in our pre-warmed AWS Lambda.

**Comment by gismya** [comment]
There is no method on the event hub right now. You should be able to reach it by using `eventHub._socketIo.disconnect()`, but `_socketIo` is marked private which means TypeScript will complain. I created a PR to add a proper method for disconnecting.

**Comment by jimmycallin** [comment]
we also have the `autoConnectEventHub` option to disable automatic connection, but not sure if that helps you. we'll fix the explicit disconnect method either way

**Comment by ffMathy** [comment]
Great suggestion, but we are actually manually connecting to the event hub, and that is needed.

**Comment by gismya** [comment]
A new release with a `disconnect()` method on `eventHub` is now out. It's currently not handling pending events in any special way, which could cause issues. Please report if you find any.
