### ISSUE TITLE
ESM issues

### ISSUE THREAD

**Issue by ffMathy** [ftrackhq/ftrack-javascript#270]
See attached screenshot:
<img width="1355" alt="image" src="https://github.com/user-attachments/assets/2e86d5ca-dbb9-4987-a758-33d34a644eb1">

**Comment by gismya** [comment]
`@ftrack/api` is only exported as an ES Module. It looks like this issue is in your project not being correctly setup for ESM. If you follow the instructions in the error message to set the file to properly be interpreted as using ESM instead of CommonJS the error should disappear.
