### ISSUE TITLE
Private methods should actually be private

### ISSUE THREAD

**Issue by ffMathy** [ftrackhq/ftrack-javascript#87]
Right now, methods (in for instance Event Hub) are just prefixed with underscores in their names. This makes them private in languages like Python, but they are still callable in TypeScript.

They should be marked with the `private` keyword.

**Comment by gismya** [comment]
This has been discussed as part of a new major version release. While they shouldn't be used they technically might be, so we've been waiting with this until we're doing that release. I'll set up a 2.0 milestone, add this issue, and create a few more issues for things we plan to get into a 2.0 release.

**Comment by ffMathy** [comment]
Great stuff!
